[build]
  command = "npm run build"
  publish = "_site"

[dev]
  command = "npm start"
  port = 8888

[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Redirect admin to CMS
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
