backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"
public_folder: "/static/img/uploads"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Blog postovi"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Naslov", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Sadržaj", name: "body", widget: "markdown"}

  - name: "videos"
    label: "Video"
    folder: "content/videos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Naslov", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Embed URL", name: "embed_url", widget: "string", hint: "YouTube: https://www.youtube.com/embed/ID"}
      - {label: "Opis", name: "description", widget: "text"}
